<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.12" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.12" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <ProjectReference Include="../Dsn.Contracts/Dsn.Contracts.csproj" />
  </ItemGroup>
</Project>
